package Green.menu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Green.util.AEClassification;
import Green.Green;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/* NCS : 수축기혈압이 140~150 또는 85-89 mmHg, 이완기혈압이 90~95 mmHg, 맥박수 101~115 회/분 또는 50~54 회/분, 체온 38.0~38.4 °C 인 경우.
 * CS : 수축기혈압이 >150 또는 <85 mmHg, 이완기혈압이 >95 mmHg, 맥박수 >115 회/분 또는 <50 회/분, 체온 >38.5°C 인 경우.
 */
//private static int[] range = new int[]{85, 89, 140, 150, 90, 95, 50, 54, 101, 115};
  /*     CS < SYS_CS_NCS <= NCS <= SYS_NCS_NORM < Normal < SYS_NORM_NCS  <= NCS <= SYS_NCS_CS < CS */
/**
 *
 * @author JHLEE
 */
public class AESettingDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    public javax.swing.JTextField[] sysJfArray;
    public javax.swing.JTextField[] diaJfArray;
    public javax.swing.JTextField[] prJfArray;

    /**
     * Creates new form AESettingDialog
     */
    public AESettingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        sysJfArray = new javax.swing.JTextField[]{
            this.SYS_CS_NCS_TF, this.SYS_NCS_NORM_TF, this.SYS_NORM_NCS_TF, this.SYS_NCS_CS_TF};
        diaJfArray = new javax.swing.JTextField[]{this.DIA_NORM_NCS_TF, this.DIA_NCS_CS_TF};
        prJfArray = new javax.swing.JTextField[]{this.PR_CS_NCS_TF, this.PR_NCS_NORM_TF, this.PR_NORM_NCS_TF, this.PR_NCS_CS_TF};

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SYS_CS_NCS_TF = new javax.swing.JTextField();
        SYS_NCS_NORM_TF = new javax.swing.JTextField();
        SYS_NORM_NCS_TF = new javax.swing.JTextField();
        SYS_NCS_CS_TF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        PR_NCS_NORM_TF = new javax.swing.JTextField();
        PR_NORM_NCS_TF = new javax.swing.JTextField();
        PR_NCS_CS_TF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        PR_CS_NCS_TF = new javax.swing.JTextField();
        DIA_NORM_NCS_TF = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        DIA_NCS_CS_TF = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        sys_CS_NCS_label = new javax.swing.JLabel();
        sys_NCS_CS_label = new javax.swing.JLabel();
        dia_NCS_CS_label = new javax.swing.JLabel();
        pr_CS_NCS_label = new javax.swing.JLabel();
        pr_NCS_CS_label = new javax.swing.JLabel();
        setInitialValueBtn = new javax.swing.JButton();

        setTitle("Clinical Significance");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("SAVE");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Systolic blood pressure (mm Hg) ");

        jLabel3.setText("NCS");

        jLabel4.setText("or");

        SYS_CS_NCS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SYS_CS_NCS_TF.setText(""+AEClassification.getRange(AEClassification.SYS_CS_NCS));
        SYS_CS_NCS_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SYS_CS_NCS_TFKeyReleased(evt);
            }
        });

        SYS_NCS_NORM_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SYS_NCS_NORM_TF.setText(""+AEClassification.getRange(AEClassification.SYS_NCS_NORM));

        SYS_NORM_NCS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SYS_NORM_NCS_TF.setText(""+AEClassification.getRange(AEClassification.SYS_NORM_NCS));

        SYS_NCS_CS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SYS_NCS_CS_TF.setText(""+AEClassification.getRange(AEClassification.SYS_NCS_CS));
        SYS_NCS_CS_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SYS_NCS_CS_TFKeyReleased(evt);
            }
        });

        jLabel20.setText("Diastolic blood pressure (mm Hg)");

        PR_NCS_NORM_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PR_NCS_NORM_TF.setText(""+AEClassification.getRange(AEClassification.PR_NCS_NORM));
        PR_NCS_NORM_TF.setMinimumSize(new java.awt.Dimension(10, 21));
        PR_NCS_NORM_TF.setName(""); // NOI18N

        PR_NORM_NCS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PR_NORM_NCS_TF.setText(""+AEClassification.getRange(AEClassification.PR_NORM_NCS));

        PR_NCS_CS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PR_NCS_CS_TF.setText(""+AEClassification.getRange(AEClassification.PR_NCS_CS));
        PR_NCS_CS_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PR_NCS_CS_TFKeyReleased(evt);
            }
        });

        jLabel26.setText("Pulse rate (bpm)");

        jLabel27.setText("CS");

        PR_CS_NCS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PR_CS_NCS_TF.setText(""+AEClassification.getRange(AEClassification.PR_CS_NCS));
        PR_CS_NCS_TF.setMinimumSize(new java.awt.Dimension(10, 21));
        PR_CS_NCS_TF.setName(""); // NOI18N
        PR_CS_NCS_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PR_CS_NCS_TFKeyReleased(evt);
            }
        });

        DIA_NORM_NCS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DIA_NORM_NCS_TF.setText(""+AEClassification.getRange(AEClassification.DIA_NORM_NCS));

        jLabel37.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel37.setText("~");

        DIA_NCS_CS_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DIA_NCS_CS_TF.setText(""+AEClassification.getRange(AEClassification.DIA_NCS_CS));
        DIA_NCS_CS_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DIA_NCS_CS_TFKeyReleased(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel40.setText("~");

        jLabel41.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel41.setText("~");

        jLabel42.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel42.setText("~");

        jLabel6.setText("or");

        jLabel45.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel45.setText("~");

        jLabel31.setText("Systolic blood pressure (mm Hg) ");

        jLabel32.setText("Diastolic blood pressure (mm Hg)");

        jLabel34.setText("Pulse rate (bpm)");

        jLabel46.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel46.setText(">");

        jLabel36.setText("or");

        jLabel47.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel47.setText("<");

        jLabel48.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel48.setText(">");

        jLabel49.setText("or");

        jLabel50.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel50.setText(">");

        jLabel51.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel51.setText("<");

        sys_CS_NCS_label.setText(SYS_CS_NCS_TF.getText());

        sys_NCS_CS_label.setText(SYS_NCS_CS_TF.getText());

        dia_NCS_CS_label.setText(DIA_NCS_CS_TF.getText());

        pr_CS_NCS_label.setText(PR_NCS_CS_TF.getText());

        pr_NCS_CS_label.setText(PR_CS_NCS_TF.getText());

        setInitialValueBtn.setText("초기화");
        setInitialValueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setInitialValueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel34)
                                .addComponent(jLabel32)))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pr_CS_NCS_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dia_NCS_CS_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sys_NCS_CS_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pr_NCS_CS_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sys_CS_NCS_label, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PR_NORM_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DIA_NORM_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SYS_NORM_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DIA_NCS_CS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(PR_NCS_CS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(PR_CS_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SYS_NCS_CS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SYS_CS_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PR_NCS_NORM_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SYS_NCS_NORM_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(setInitialValueBtn)))
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SYS_CS_NCS_TF, SYS_NCS_CS_TF, SYS_NCS_NORM_TF, SYS_NORM_NCS_TF});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DIA_NCS_CS_TF, DIA_NORM_NCS_TF});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PR_CS_NCS_TF, PR_NCS_CS_TF, PR_NCS_NORM_TF, PR_NORM_NCS_TF});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pr_NCS_CS_label, sys_CS_NCS_label});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(setInitialValueBtn)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SYS_CS_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(SYS_NORM_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SYS_NCS_CS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SYS_NCS_NORM_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(DIA_NORM_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DIA_NCS_CS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(PR_NCS_CS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PR_NORM_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PR_CS_NCS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PR_NCS_NORM_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel27)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sys_CS_NCS_label)
                    .addComponent(sys_NCS_CS_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia_NCS_CS_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pr_CS_NCS_label)
                        .addComponent(pr_NCS_CS_label)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(20, 20, 20))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            StringBuffer sb = new StringBuffer("*,");
            int[] newRange = new int[AEClassification.getRangeLength()];
            if (!isInOrder(sb, newRange)) {
                Green.message("입력값이 잘못되었습니다. 다시 입력하여 주십시오.");
                return;
            }

            AEClassification.setRange(newRange);

            if (saveToConFigFile(sb.toString())) {
                doClose(RET_OK);
            }

        } catch (FileNotFoundException ex) {
            Green.message("설정 파일이 존재하지 않습니다. 확인하여주시기 바랍니다." + Green.DIR + "\\config\\range.txt");

        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void SYS_NCS_CS_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SYS_NCS_CS_TFKeyReleased
        sys_NCS_CS_label.setText(SYS_NCS_CS_TF.getText());
    }//GEN-LAST:event_SYS_NCS_CS_TFKeyReleased

    private void SYS_CS_NCS_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SYS_CS_NCS_TFKeyReleased
        sys_CS_NCS_label.setText(SYS_CS_NCS_TF.getText());
    }//GEN-LAST:event_SYS_CS_NCS_TFKeyReleased

    private void DIA_NCS_CS_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DIA_NCS_CS_TFKeyReleased
        dia_NCS_CS_label.setText(DIA_NCS_CS_TF.getText());
    }//GEN-LAST:event_DIA_NCS_CS_TFKeyReleased

    private void PR_NCS_CS_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PR_NCS_CS_TFKeyReleased
        pr_CS_NCS_label.setText(PR_NCS_CS_TF.getText());
    }//GEN-LAST:event_PR_NCS_CS_TFKeyReleased

    private void PR_CS_NCS_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PR_CS_NCS_TFKeyReleased
        pr_NCS_CS_label.setText(PR_CS_NCS_TF.getText());
    }//GEN-LAST:event_PR_CS_NCS_TFKeyReleased

    private void setInitialValueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setInitialValueBtnActionPerformed
        this.SYS_NORM_NCS_TF.setText("140");
        this.SYS_NCS_CS_TF.setText("150");
        this.SYS_CS_NCS_TF.setText("85");
        this.SYS_NCS_NORM_TF.setText("89");
        this.DIA_NORM_NCS_TF.setText("90");
        this.DIA_NCS_CS_TF.setText("95");
        this.PR_NORM_NCS_TF.setText("101");
        this.PR_NCS_CS_TF.setText("115");
        this.PR_CS_NCS_TF.setText("50");
        this.PR_NCS_NORM_TF.setText("54");
        sys_NCS_CS_label.setText(SYS_NCS_CS_TF.getText());
        sys_CS_NCS_label.setText(SYS_CS_NCS_TF.getText());
        pr_NCS_CS_label.setText(PR_CS_NCS_TF.getText());
        dia_NCS_CS_label.setText(DIA_NCS_CS_TF.getText());
        pr_CS_NCS_label.setText(PR_NCS_CS_TF.getText());
    }//GEN-LAST:event_setInitialValueBtnActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AESettingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AESettingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AESettingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AESettingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                AESettingDialog dialog = new AESettingDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DIA_NCS_CS_TF;
    private javax.swing.JTextField DIA_NORM_NCS_TF;
    private javax.swing.JTextField PR_CS_NCS_TF;
    private javax.swing.JTextField PR_NCS_CS_TF;
    private javax.swing.JTextField PR_NCS_NORM_TF;
    private javax.swing.JTextField PR_NORM_NCS_TF;
    private javax.swing.JTextField SYS_CS_NCS_TF;
    private javax.swing.JTextField SYS_NCS_CS_TF;
    private javax.swing.JTextField SYS_NCS_NORM_TF;
    private javax.swing.JTextField SYS_NORM_NCS_TF;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dia_NCS_CS_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pr_CS_NCS_label;
    private javax.swing.JLabel pr_NCS_CS_label;
    private javax.swing.JButton setInitialValueBtn;
    private javax.swing.JLabel sys_CS_NCS_label;
    private javax.swing.JLabel sys_NCS_CS_label;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    private boolean saveToConFigFile(String s) throws FileNotFoundException {

        File file = new File(Green.DIR + "/config/range.txt");

        try {
            FileWriter writer = new FileWriter(file, false);
            writer.write(s + "*");
            writer.close();
        } catch (IOException ex) {
            Green.message("파일을 저장할 수 없습니다." + file.getAbsolutePath());

        }
        return true;
    }

    private boolean isInOrder(StringBuffer buffer, int[] newRange) {

        try {
            int index = 0;
//             sysJfArray
//        diaJfArray
//        prJfArray 

            for (int i = 0; i < sysJfArray.length; i++) {
                JTextField jf = sysJfArray[i];
                if (Green.DEBUG) {
                    System.out.println("\t NCS CS setting value= " + jf.getText());
                }

                int value = Integer.parseInt(jf.getText());
                if (i != 0 && value < newRange[index - 1]) {
                    return false;
                }
                buffer.append(value + ",");
                newRange[index++] = value;
            }
            for (int i = 0; i < diaJfArray.length; i++) {
                JTextField jf = diaJfArray[i];
                if (Green.DEBUG) {
                    System.out.println("\t NCS CS setting value= " + jf.getText());
                }

                int value = Integer.parseInt(jf.getText());
                if (i != 0 && value < newRange[index - 1]) {
                    return false;
                }
                buffer.append(value + ",");
                newRange[index++] = value;
            }
            for (int i = 0; i < prJfArray.length; i++) {
                JTextField jf = prJfArray[i];
                if (Green.DEBUG) {
                    System.out.println("\t NCS CS setting value= " + jf.getText());
                }

                int value = Integer.parseInt(jf.getText());
                if (i != 0 && value < newRange[index - 1]) {
                    return false;
                }
                buffer.append(value + ",");
                newRange[index++] = value;
            }
        } catch (Exception e) {
            return false;
        }

        return true;
    }

    private boolean isInOrder(JTextField[] jfarray, StringBuffer buffer) {

        try {
            int tmp = 0;

            for (int i = 0; i < jfarray.length; i++) {
                JTextField jf = jfarray[i];
                if (Green.DEBUG) {
                    System.out.println("\t NCS CS setting value= " + jf.getText());
                }

                int value = Integer.parseInt(jf.getText());
                if (value < tmp) {
                    return false;
                }
                tmp = value;
                buffer.append(value + ",");
            }
        } catch (Exception e) {
            return false;
        }

        return true;
    }
}
